//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KenJobs.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            this.AppliedJobs = new HashSet<AppliedJob>();
            this.FavoriteJobs = new HashSet<FavoriteJob>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Client_Id { get; set; }
        public string JobTitle { get; set; }
        public string Description { get; set; }
        public Nullable<int> NoOfVacancies { get; set; }
        public Nullable<double> MinSalary { get; set; }
        public string Qualification { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public System.DateTime PostDate { get; set; }
        public short Status { get; set; }
        public short PostingStatus { get; set; }
        public int JobType_Id { get; set; }
        public int Category_id { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public Nullable<double> MinExperience { get; set; }
        public string Skills { get; set; }
        public Nullable<double> MaxSalary { get; set; }
        public Nullable<double> MaxExperience { get; set; }
        public Nullable<int> User_Id { get; set; }
        public Nullable<int> Currency { get; set; }
        public string ClientName { get; set; }
        public string Country { get; set; }
        public string AddressLine { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppliedJob> AppliedJobs { get; set; }
        public virtual JobCategory JobCategory { get; set; }
        public virtual JobType JobType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FavoriteJob> FavoriteJobs { get; set; }
    }
}
