//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KenJobs.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public int Id { get; set; }
        public int Country_Id { get; set; }
        public string Name { get; set; }
        public short Status { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual Country Country { get; set; }
    }
}
