//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KenJobs.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAttachment
    {
        public int Id { get; set; }
        public int User_Id { get; set; }
        public int Attachment_Id { get; set; }
        public int AttachmentType_Id { get; set; }
        public string Name { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual Attachment Attachment { get; set; }
        public virtual AttachmentType AttachmentType { get; set; }
        public virtual User User { get; set; }
    }
}
